// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PracticaProfesional.Infrastructure.Persistence;

#nullable disable

namespace PracticaProfesional.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414000002_AddLogSeguridad")]
    partial class AddLogSeguridad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PracticaProfesional.Domain.Entities.LogSeguridad", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Email").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                    b.Property<bool>("Exitoso").HasColumnType("bit");
                    b.Property<string>("MotivoFallo").HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("IpOrigen").IsRequired().HasMaxLength(45).HasColumnType("nvarchar(45)");
                    b.Property<string>("UserAgent").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<DateTime>("Timestamp").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("Email");
                    b.HasIndex("Exitoso");
                    b.HasIndex("Timestamp");
                    b.ToTable("LogsSeguridad");
                });
#pragma warning restore 612, 618
        }
    }
}
