// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticaProfesional.Infrastructure.Persistence;

#nullable disable

namespace PracticaProfesional.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414000001_AddAuditoriaLogs")]
    partial class AddAuditoriaLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PracticaProfesional.Domain.Entities.AuditoriaLog", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Accion").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<string>("EjecutorEmail").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                    b.Property<int?>("EjecutorId").HasColumnType("int");
                    b.Property<string>("EntidadId").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<string>("EntidadTipo").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<DateTime>("Timestamp").HasColumnType("datetime2");
                    b.Property<string>("ValorAnterior").HasColumnType("nvarchar(max)");
                    b.Property<string>("ValorNuevo").HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("Accion");
                    b.HasIndex("EntidadTipo");
                    b.HasIndex("Timestamp");
                    b.ToTable("AuditoriaLogs");
                });

            modelBuilder.Entity("PracticaProfesional.Domain.Entities.AuditoriaCambioRol", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Accion").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<string>("RolOriginal").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("RolVista").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<DateTime>("Timestamp").HasColumnType("datetime2");
                    b.Property<int>("UsuarioId").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("UsuarioId");
                    b.ToTable("AuditoriaCambiosRol");
                });

            modelBuilder.Entity("PracticaProfesional.Domain.Entities.Docente", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("UsuarioId").HasColumnType("int");
                    b.Property<string>("Telefono").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<string>("Categoria").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.HasKey("Id");
                    b.HasIndex("UsuarioId").IsUnique();
                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("PracticaProfesional.Domain.Entities.Preceptor", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("UsuarioId").HasColumnType("int");
                    b.Property<string>("Telefono").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<string>("Turno").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.HasKey("Id");
                    b.HasIndex("UsuarioId").IsUnique();
                    b.ToTable("Preceptores");
                });

            modelBuilder.Entity("PracticaProfesional.Domain.Entities.Estudiante", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("UsuarioId").HasColumnType("int");
                    b.Property<int>("Anio").HasColumnType("int");
                    b.Property<string>("Condicion").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("FechaDeIngreso").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("UsuarioId").IsUnique();
                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("PracticaProfesional.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Apellido").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<bool>("Activo").ValueGeneratedOnAdd().HasColumnType("bit").HasDefaultValue(true);
                    b.Property<string>("DNI").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)");
                    b.Property<string>("Email").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                    b.Property<DateTime>("FechaCreacion").HasColumnType("datetime2");
                    b.Property<string>("Legajo").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<string>("Nombre").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("PasswordHash").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("PasswordResetToken").HasMaxLength(64).HasColumnType("nvarchar(64)");
                    b.Property<DateTime?>("PasswordResetTokenExpiry").HasColumnType("datetime2");
                    b.Property<string>("Rol").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("DNI").IsUnique();
                    b.HasIndex("Email").IsUnique();
                    b.HasIndex("Legajo").IsUnique();
                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PracticaProfesional.Domain.Entities.AuditoriaCambioRol", b =>
                {
                    b.HasOne("PracticaProfesional.Domain.Entities.Usuario", null)
                        .WithMany().HasForeignKey("UsuarioId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                });

            modelBuilder.Entity("PracticaProfesional.Domain.Entities.Docente", b =>
                {
                    b.HasOne("PracticaProfesional.Domain.Entities.Usuario", "Usuario")
                        .WithOne().HasForeignKey("PracticaProfesional.Domain.Entities.Docente", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PracticaProfesional.Domain.Entities.Preceptor", b =>
                {
                    b.HasOne("PracticaProfesional.Domain.Entities.Usuario", "Usuario")
                        .WithOne().HasForeignKey("PracticaProfesional.Domain.Entities.Preceptor", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PracticaProfesional.Domain.Entities.Estudiante", b =>
                {
                    b.HasOne("PracticaProfesional.Domain.Entities.Usuario", "Usuario")
                        .WithOne().HasForeignKey("PracticaProfesional.Domain.Entities.Estudiante", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
